Students = int(input("How many students are there?"))
Apples = int(input("How many apples are there?"))
AperS = int(Students//Apples)
Left = int(Students%Apples)
print("There are {} apples per student.".format(AperS))
print("There are {} apples left.".format(Left))
