line = str(input("Enter a string: "))
linelen = int(len(line))
print(line[3])
print(line[linelen-2])
print(line[0:5])
print(line[0:linelen-2])
print(line[0::2])
print(line[1::2])
print(line[::-1])
print(line[linelen::-2])
print(str(linelen))